export const HUB_TEST_DATA = [
  {
    id: 1,
    name: { label: "Acme Corp", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Active",
    revenue: "$1.2M",
    owner: "Emma Dupont",
    priority: "High",
    tags: [{ label: "Enterprise" }, { label: "Renewal" }, { label: "Q2" }],
    stage: { text: "Review", iconName: "DocumentText" },
    isActive: true,
    notes: "Ready for legal",
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 2,
    name: { label: "Blue Sky", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Pending",
    revenue: "$480K",
    owner: "Thomas Bernard",
    priority: "Medium",
    tags: [{ label: "New" }, { label: "EMEA" }, { label: "Q3" }],
    stage: { text: "Draft", iconName: "PencilSquare" },
    isActive: false,
    notes: "Waiting for budget",
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 3,
    name: { label: "North Star", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Active",
    revenue: "$2.1M",
    owner: "Sophie Martin",
    priority: "High",
    tags: [{ label: "Upsell" }, { label: "Strategic" }, { label: "Q1" }],
    stage: { text: "Approved", iconName: "CheckCircle" },
    isActive: true,
    notes: "Contract in progress",
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 4,
    name: { label: "Horizon Inc", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Active",
    revenue: "$750K",
    owner: "Luca Romano",
    priority: "Low",
    tags: [{ label: "Mid-Market" }, { label: "Expansion" }, { label: "Q4" }],
    stage: { text: "Negotiation", iconName: "ChatBubbleLeftRight" },
    isActive: true,
    notes: "Need updated scope",
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 5,
    name: { label: "Apex Partners", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Pending",
    revenue: "$310K",
    owner: "Anna Kovacs",
    priority: "Medium",
    tags: [{ label: "Pilot" }, { label: "SMB" }, { label: "Q2" }],
    stage: { text: "Discovery", iconName: "MagnifyingGlass" },
    isActive: false,
    notes: "Collect requirements",
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
];

export const AI_OPPORTUNITY_DATA = [
  {
    id: 1,
    name: { label: "Acme Corp - Cloud Migration", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Active",
    confidence: "High",
    value: "$320K",
    owner: "Emma Dupont",
    source: "Email",
    tags: [{ label: "Cloud" }, { label: "Q2" }],
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 2,
    name: { label: "Blue Sky - Data Platform", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Pending",
    confidence: "Medium",
    value: "$180K",
    owner: "Thomas Bernard",
    source: "CRM",
    tags: [{ label: "Data" }, { label: "Q3" }],
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
  {
    id: 3,
    name: { label: "North Star - AI Expansion", href: "#", iconLeadingName: "BuildingOffice2" },
    status: "Active",
    confidence: "High",
    value: "$540K",
    owner: "Sophie Martin",
    source: "Meeting Notes",
    tags: [{ label: "AI" }, { label: "Strategic" }],
    action: { iconName: "EllipsisVertical", iconOnly: true, ariaLabel: "Row actions" },
  },
];

export const ASSET_TYPES = [
  {
    value: "pharma",
    label: "Pharma asset",
    description: "Molecules or products aimed at licensing or collaboration projects",
    iconName: "Beaker",
  },
  {
    value: "technology",
    label: "Technology",
    description: "Digital health, medical devices or other technology solutions",
    iconName: "CpuChip",
  },
  {
    value: "organization",
    label: "Organization asset",
    description: "Potential partners for out-licensing, M&A, investment, or landscaping",
    iconName: "BuildingOffice2",
  },
  {
    value: "consumer",
    label: "Consumer health asset",
    description: "Consumer health molecules, products, ingredients or technologies",
    iconName: "Heart",
  },
];
