/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./library/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./*.jsx",
    "./eureka.jsx",
  ],
  theme: {
    extend: {
      fontFamily: {
        primary: ["Sora", "sans-serif"],
        secondary: ["Lato", "sans-serif"],
      },
      colors: {
        // Primitive Colors
        primary: {
          25: "var(--color-primary-25)",
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
        neutral: {
          0: "var(--color-neutral-0)",
          25: "var(--color-neutral-25)",
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        success: {
          25: "var(--color-success-25)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
        },
        error: {
          25: "var(--color-error-25)",
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
        },
        warning: {
          25: "var(--color-warning-25)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
        },
        // Semantic Colors
        content: {
          primary: "var(--color-content-primary)",
          secondary: "var(--color-content-secondary)",
          tertiary: "var(--color-content-tertiary)",
          inverted: "var(--color-content-inverted)",
          brand: "var(--color-content-brand)",
          "brand-bold": "var(--color-content-brand-bold)",
          positive: "var(--color-content-positive)",
          negative: "var(--color-content-negative)",
          warning: "var(--color-content-warning)",
          informative: "var(--color-content-informative)",
        },
        background: {
          white: "var(--color-background-white)",
          "neutral-lighter": "var(--color-background-neutral-lighter)",
          "neutral-light": "var(--color-background-neutral-light)",
          "neutral-dark": "var(--color-background-neutral-dark)",
          positive: "var(--color-background-positive)",
          negative: "var(--color-background-negative)",
          "negative-light": "var(--color-background-negative-light)",
          warning: "var(--color-background-warning)",
          "warning-light": "var(--color-background-warning-light)",
          informative: "var(--color-background-informative)",
          avatar: "var(--color-background-avatar)",
        },
        outline: {
          neutral: "var(--color-outline-neutral)",
          "neutral-light": "var(--color-outline-neutral-light)",
        },
        // Action Colors
        action: {
          "fill-primary": "var(--color-action-fill-primary-enabled)",
          "fill-primary-hover": "var(--color-action-fill-primary-hover)",
          "fill-primary-active": "var(--color-action-fill-primary-active)",
          "fill-primary-disabled": "var(--color-action-fill-primary-disabled)",
          "fill-secondary": "var(--color-action-fill-secondary-enabled)",
          "fill-secondary-hover": "var(--color-action-fill-secondary-hover)",
          "fill-secondary-active": "var(--color-action-fill-secondary-active)",
          "fill-secondary-disabled": "var(--color-action-fill-secondary-disabled)",
          "fill-tertiary": "var(--color-action-fill-tertiary-enabled)",
          "fill-tertiary-hover": "var(--color-action-fill-tertiary-hover)",
          "fill-tertiary-active": "var(--color-action-fill-tertiary-active)",
          "fill-negative": "var(--color-action-fill-negative-enabled)",
          "fill-negative-hover": "var(--color-action-fill-negative-hover)",
          "content-primary": "var(--color-action-content-primary-enabled)",
          "content-secondary": "var(--color-action-content-secondary-enabled)",
          "content-secondary-hover": "var(--color-action-content-secondary-hover)",
          "content-tertiary": "var(--color-action-content-tertiary-enabled)",
          "content-tertiary-hover": "var(--color-action-content-tertiary-hover)",
          "content-negative": "var(--color-action-content-negative-enabled)",
          "content-link": "var(--color-action-content-link-enabled)",
          "content-link-hover": "var(--color-action-content-link-hover)",
          "outline-secondary": "var(--color-action-outline-secondary-enabled)",
          "outline-secondary-hover": "var(--color-action-outline-secondary-hover)",
        },
        interaction: {
          fill: "var(--color-interaction-fill-enabled)",
          "fill-hover": "var(--color-interaction-fill-hover)",
          "fill-disabled": "var(--color-interaction-fill-disabled)",
          "fill-search": "var(--color-interaction-fill-search)",
          outline: "var(--color-interaction-outline-enabled)",
          "outline-hover": "var(--color-interaction-outline-hover)",
          "outline-active": "var(--color-interaction-outline-active)",
          "outline-disabled": "var(--color-interaction-outline-disabled)",
          "outline-negative": "var(--color-interaction-outline-negative)",
        },
      },
      spacing: {
        "0.5": "var(--spacing-0-5)",
        "1": "var(--spacing-1)",
        "1.5": "var(--spacing-1-5)",
        "2": "var(--spacing-2)",
        "2.5": "var(--spacing-2-5)",
        "3": "var(--spacing-3)",
        "3.5": "var(--spacing-3-5)",
        "4": "var(--spacing-4)",
        "5": "var(--spacing-5)",
        "6": "var(--spacing-6)",
        "7": "var(--spacing-7)",
        "8": "var(--spacing-8)",
        "9": "var(--spacing-9)",
        "10": "var(--spacing-10)",
        "11": "var(--spacing-11)",
        "12": "var(--spacing-12)",
        "14": "var(--spacing-14)",
        "16": "var(--spacing-16)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        focus: "var(--shadow-focus)",
        "light-up": "var(--shadow-light-up)",
        "light-down": "var(--shadow-light-down)",
        "medium-up": "var(--shadow-medium-up)",
        "medium-down": "var(--shadow-medium-down)",
        "dark-up": "var(--shadow-dark-up)",
        "dark-down": "var(--shadow-dark-down)",
      },
      fontSize: {
        "heading-h1": ["var(--text-heading-h1)", { lineHeight: "var(--line-height-heading-h1)", fontWeight: "var(--font-weight-heading-h1)" }],
        "heading-h2": ["var(--text-heading-h2)", { lineHeight: "var(--line-height-heading-h2)", fontWeight: "var(--font-weight-heading-h2)" }],
        "heading-h3": ["var(--text-heading-h3)", { lineHeight: "var(--line-height-heading-h3)", fontWeight: "var(--font-weight-heading-h3)" }],
        "heading-h4": ["var(--text-heading-h4)", { lineHeight: "var(--line-height-heading-h4)", fontWeight: "var(--font-weight-heading-h4)" }],
        "body-xl": ["var(--text-body-xl)", { lineHeight: "var(--line-height-body-xl)" }],
        "body-lg": ["var(--text-body-lg)", { lineHeight: "var(--line-height-body-lg)" }],
        "body-md": ["var(--text-body-md)", { lineHeight: "var(--line-height-body-md)" }],
        "body-caption": ["var(--text-body-caption)", { lineHeight: "var(--line-height-body-caption)" }],
        "highlight-lg": ["var(--text-highlight-lg)", { lineHeight: "var(--line-height-highlight-lg)", fontWeight: "var(--font-weight-highlight-lg)" }],
        "highlight-md": ["var(--text-highlight-md)", { lineHeight: "var(--line-height-highlight-md)", fontWeight: "var(--font-weight-highlight-md)" }],
        "button-lg": ["var(--text-button-lg)", { lineHeight: "var(--line-height-button-lg)" }],
        "button-md": ["var(--text-button-md)", { lineHeight: "var(--line-height-button-md)" }],
      },
      transitionDuration: {
        fast: "150ms",
        normal: "200ms",
        slow: "300ms",
      },
      width: {
        "icon-xs": "var(--size-icon-xs)",
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "icon-xl": "var(--size-icon-xl)",
        "avatar-xs": "var(--size-avatar-xs)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "avatar-xl": "var(--size-avatar-xl)",
        "avatar-2xl": "var(--size-avatar-2xl)",
        "modal-sm": "var(--size-modal-sm)",
        "modal-md": "var(--size-modal-md)",
        "modal-lg": "var(--size-modal-lg)",
        "modal-xl": "var(--size-modal-xl)",
      },
      height: {
        "icon-xs": "var(--size-icon-xs)",
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "icon-xl": "var(--size-icon-xl)",
        "avatar-xs": "var(--size-avatar-xs)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "avatar-xl": "var(--size-avatar-xl)",
        "avatar-2xl": "var(--size-avatar-2xl)",
        "button-xs": "var(--size-button-xs)",
        "button-sm": "var(--size-button-sm)",
        "button-md": "var(--size-button-md)",
        "button-lg": "var(--size-button-lg)",
        "button-xl": "var(--size-button-xl)",
        "input-sm": "var(--size-input-sm)",
        "input-md": "var(--size-input-md)",
        "input-lg": "var(--size-input-lg)",
      },
      minHeight: {
        "button-xs": "var(--size-button-xs)",
        "button-sm": "var(--size-button-sm)",
        "button-md": "var(--size-button-md)",
        "button-lg": "var(--size-button-lg)",
        "button-xl": "var(--size-button-xl)",
        "input-sm": "var(--size-input-sm)",
        "input-md": "var(--size-input-md)",
        "input-lg": "var(--size-input-lg)",
      },
      size: {
        "icon-xs": "var(--size-icon-xs)",
        "icon-sm": "var(--size-icon-sm)",
        "icon-md": "var(--size-icon-md)",
        "icon-lg": "var(--size-icon-lg)",
        "icon-xl": "var(--size-icon-xl)",
        "avatar-xs": "var(--size-avatar-xs)",
        "avatar-sm": "var(--size-avatar-sm)",
        "avatar-md": "var(--size-avatar-md)",
        "avatar-lg": "var(--size-avatar-lg)",
        "avatar-xl": "var(--size-avatar-xl)",
        "avatar-2xl": "var(--size-avatar-2xl)",
      },
    },
  },
  plugins: [],
};
